-- 0025: seed agr_templates v1.0 from content/legal/*.md (generated by scripts/portal-seed-templates.mjs).
-- Apply with: wrangler d1 execute aanloop-portal --remote --file=migrations/0025_overeenkomst_templates_seed.sql
INSERT OR IGNORE INTO agr_templates (id, slug, version, title, body_markdown, effective_from, created_at) VALUES ('tpl_overeenkomst_1_0', 'overeenkomst', '1.0', 'Overeenkomst van opdracht', '# Overeenkomst van opdracht

**Opdrachtnemer:** AanloopAI, handelsnaam van Mustafa Dogan, gevestigd aan de Blokfluit 31, 3068 KZ Rotterdam, KvK 88606902, btw NL004672676B48, e-mail m.dogan@aanloopai.nl (hierna: "AanloopAI").

**Opdrachtgever:** {{klant_bedrijfsnaam}} ({{klant_rechtsvorm}}), gevestigd te {{klant_adres}}, {{klant_postcode}} {{klant_plaats}}, KvK {{klant_kvk}}, btw {{klant_btw}}, vertegenwoordigd door {{klant_contact_naam}} (hierna: "Opdrachtgever").

Referentie: {{agreement_id}} · Datum: {{datum}}

## 1. Onderwerp

AanloopAI levert aan Opdrachtgever het project **{{project_naam}}** op het domein **{{project_domein}}**, bestaande uit de onderdelen in artikel 2 t/m 5. Op deze overeenkomst zijn de Algemene Voorwaarden van AanloopAI (Bijlage B) en de Privacyverklaring en Verwerkersovereenkomst (Bijlage C) van toepassing; Opdrachtgever heeft deze gelezen en aanvaard.

## 2. Website — eenmalig {{prijs_website}} excl. btw

Omvang:
- Pagina''s: home, keukens per stijl, alles onder één dak, over ons, Keukenkompas, contact & afspraak
- Afspraakmodule gekoppeld aan de agenda van Opdrachtgever
- WhatsApp-knop en contactformulier
- Lokale pagina''s voor de door Opdrachtgever opgegeven plaatsen
- Google Business Profile aanmaken; Analytics, Search Console en Meta Pixel koppelen
- Privacyverklaring en cookiebeleid voor de site van Opdrachtgever
- Teksten in samenwerking: Opdrachtgever levert inhoud, AanloopAI schrijft en redigeert
- Styling-beelden per keukenstijl; foto''s van geplaatste keukens zodra Opdrachtgever deze met toestemming aanlevert
- Subtiele scroll-animaties; hosting en domeinkoppeling op {{project_domein}}

Betaling: {{betaling_fasen}}. Betaaltermijn {{betaaltermijn_dagen}} dagen.

Optie cinematic 3D-beleving ({{prijs_optie_3d}} excl. btw): gekozen = **{{optie_3d_gekozen}}**.

## 3. Beheer & groei — {{prijs_beheer_maand}} per maand excl. btw

Doorlopend werk om de leadstroom van de site maand na maand te laten groeien: zoekmachineoptimalisatie, nieuwe lokale en inhoudelijke pagina''s, conversieverbeteringen op basis van de cijfers, Google Business Profile, geautomatiseerde reviewvraag na montage, maandrapportage, hosting en onderhoud.

Start: bij livegang. Maandelijks vooraf gefactureerd. Maandelijks opzegbaar met een opzegtermijn van één kalendermaand. AanloopAI voert geen betaalde advertenties uit en beheert geen advertentiebudget.

## 4. Leads — {{prijs_lead}} per lead excl. btw

- Levering via het leadplatform van AanloopAI (o.a. keukeninbeeld.nl), exclusief binnen {{lead_regio}}, maximaal {{lead_cap_per_dag}} leads per dag.
- Levering per e-mail en WhatsApp aan {{klant_dagelijks_contact}}.
- Afname in bundels van {{lead_bundel_aantal}} leads ({{lead_bundel_prijs}} excl. btw), vooraf gefactureerd. Een bundel is 12 maanden geldig.
- Een ongeldige lead meldt Opdrachtgever via het portaal binnen 2 werkdagen na levering (bij onbereikbaarheid binnen 5 werkdagen, na ten minste drie belpogingen en één schriftelijke poging). De gronden, termijnen en de vervangingsregeling staan in Module C, artikel C5 van de Algemene Voorwaarden. Een gegronde melding leidt tot vervanging of niet-afboeking van de bundel; er vindt geen terugbetaling in geld plaats. Een lead die niet tot een opdracht leidt, is geen ongeldige lead.
- Opdrachtgever volgt elke lead binnen één werkdag op.

## 5. Fase 2 — ontwerptool

De ontwerptool (plattegrond, 3D, render, prijsindicatie, koppeling) valt buiten deze overeenkomst en wordt na een aparte discovery in een apart voorstel aangeboden.

## 6. Aanlevering en planning

Opdrachtgever levert de in het portaal genoemde bestanden en gegevens aan (logo, foto''s, toegangen, teksten). Livegang: binnen 4 weken na volledige aanlevering en betaling van de eerste termijn. Vertraging in aanlevering schuift de planning evenredig op.

## 7. Eigendom

Na volledige betaling van artikel 2 gaan de site, de teksten en de broncode van de site over op Opdrachtgever. Generieke componenten, tooling en het leadplatform van AanloopAI blijven eigendom van AanloopAI (zie Algemene Voorwaarden artikel 9).

## 8. Contact en akkoorden

Wekelijkse update via WhatsApp. Akkoorden worden gegeven door {{klant_contact_naam}}; dagelijks aanspreekpunt is {{klant_dagelijks_contact}}.

## 9. Ondertekening

Deze overeenkomst wordt digitaal ondertekend via het klantenportaal van AanloopAI (artikel 11 van de Algemene Voorwaarden). De ondertekeningspagina met audit trail maakt deel uit van deze overeenkomst. Namens AanloopAI is deze overeenkomst vooraf ondertekend door Mustafa Dogan.
', 1760000000000, 1760000000000);
INSERT OR IGNORE INTO agr_templates (id, slug, version, title, body_markdown, effective_from, created_at) VALUES ('tpl_av_1_0', 'algemene-voorwaarden', '1.0', 'Algemene Voorwaarden AanloopAI', '# Algemene Voorwaarden AanloopAI

**Versie 1.0 — geldig vanaf 9 oktober 2026**

AanloopAI is een handelsnaam van Mustafa Dogan, gevestigd aan de Blokfluit 31, 3068 KZ Rotterdam, ingeschreven bij de Kamer van Koophandel onder nummer 88606902, btw-identificatienummer NL004672676B48, e-mail m.dogan@aanloopai.nl.

Deze voorwaarden bestaan uit een **Algemeen deel** (artikel 1 t/m 20) dat op alle diensten van toepassing is, en drie **modules** die gelden voor zover de betreffende dienst is overeengekomen: **Module A — Websites en ontwikkeling**, **Module B — Beheer en doorlopende diensten**, **Module C — Leads**. Bij strijdigheid gaat een module voor op het Algemeen deel, en gaat de Overeenkomst voor op beide.

---

## ALGEMEEN DEEL

### Artikel 1 — Definities

1.1 **AanloopAI**: de opdrachtnemer, zoals hierboven omschreven, inclusief de onder deze handelsnaam gevoerde platforms en labels.

1.2 **Opdrachtgever**: de natuurlijke persoon handelend in de uitoefening van beroep of bedrijf, of de rechtspersoon, die met AanloopAI een Overeenkomst sluit of daartoe een aanbod ontvangt.

1.3 **Overeenkomst**: iedere afspraak tussen AanloopAI en Opdrachtgever, waaronder het door Opdrachtgever aanvaarde voorstel, de opdrachtbevestiging en deze voorwaarden, inclusief bijlagen.

1.4 **Diensten**: alle door AanloopAI te leveren werkzaamheden en producten, waaronder het ontwerpen en bouwen van websites en software, automatisering, AI-agents (chat, spraak, WhatsApp), hosting, beheer, zoekmachineoptimalisatie, rapportage en het leveren van Leads.

1.5 **Lead**: de contact- en aanvraaggegevens van een natuurlijke persoon of bedrijf dat via een platform van AanloopAI heeft aangegeven interesse te hebben in een product of dienst en daarbij toestemming heeft gegeven om door een aangesloten ondernemer te worden benaderd.

1.6 **Platform**: een door AanloopAI geëxploiteerde website of ander kanaal waarop aanvragen worden verzameld, waaronder keukeninbeeld.nl en zoekeen.nl.

1.7 **Portaal**: het klantenportaal "Mijn AanloopAI" op aanloopai.nl, waarin Opdrachtgever documenten leest en ondertekent, bestanden aanlevert en meldingen doet.

1.8 **Schriftelijk**: per brief, e-mail of via het Portaal.

1.9 **Werk**: alle door AanloopAI in het kader van de Overeenkomst ontwikkelde of geleverde resultaten, zoals ontwerpen, teksten, beelden, code, configuraties, documentatie en rapportages.

### Artikel 2 — Toepasselijkheid

2.1 Deze voorwaarden zijn van toepassing op alle aanbiedingen, voorstellen, Overeenkomsten en leveringen van AanloopAI.

2.2 De toepasselijkheid van inkoop- of andere voorwaarden van Opdrachtgever wordt uitdrukkelijk van de hand gewezen.

2.3 Afwijkingen van deze voorwaarden zijn alleen geldig als zij Schriftelijk zijn overeengekomen en gelden uitsluitend voor de Overeenkomst waarvoor zij zijn gemaakt.

2.4 AanloopAI levert uitsluitend aan ondernemers. Opdrachtgever verklaart te handelen in de uitoefening van beroep of bedrijf. De wettelijke bepalingen ter bescherming van consumenten zijn niet van toepassing.

2.5 Als een bepaling van deze voorwaarden nietig is of wordt vernietigd, blijven de overige bepalingen van kracht. Partijen vervangen de nietige bepaling door een geldige bepaling die de bedoeling van de oorspronkelijke bepaling zo dicht mogelijk benadert.

### Artikel 3 — Aanbod en totstandkoming

3.1 Alle voorstellen en offertes van AanloopAI zijn vrijblijvend en 30 dagen geldig, tenzij anders vermeld.

3.2 Een Overeenkomst komt tot stand op het moment dat (a) Opdrachtgever het voorstel digitaal ondertekent in het Portaal, (b) Opdrachtgever het voorstel Schriftelijk aanvaardt, of (c) AanloopAI op verzoek van Opdrachtgever met de uitvoering begint.

3.3 Een voorstel is gebaseerd op de door Opdrachtgever verstrekte informatie. Blijkt die informatie onjuist of onvolledig, dan mag AanloopAI het voorstel aanpassen.

3.4 Kennelijke vergissingen of verschrijvingen in een voorstel binden AanloopAI niet.

3.5 Voorstellen gelden niet automatisch voor toekomstige opdrachten.

### Artikel 4 — Prijzen

4.1 Alle prijzen zijn in euro''s en exclusief btw en andere heffingen van overheidswege.

4.2 Prijzen voor doorlopende diensten mag AanloopAI eenmaal per kalenderjaar aanpassen. Een verhoging wordt ten minste één maand vooraf Schriftelijk aangekondigd. Bedraagt de verhoging meer dan 10%, dan mag Opdrachtgever de betreffende dienst tegen de ingangsdatum opzeggen.

4.3 Werkzaamheden buiten de overeengekomen omvang (meerwerk) worden pas uitgevoerd na Schriftelijk akkoord van Opdrachtgever en worden gefactureerd tegen het dan geldende uurtarief van AanloopAI, tenzij een vaste prijs is afgesproken. Het ontstaan van meerwerk is voor Opdrachtgever nooit grond voor opzegging of ontbinding.

### Artikel 5 — Betaling

5.1 Eenmalige projecten worden gefactureerd in de fasen die in de Overeenkomst zijn vermeld. Tenzij anders overeengekomen geldt: 30% bij akkoord, 40% bij akkoord op het ontwerp, 30% bij oplevering of livegang. AanloopAI mag de volgende fase pas starten na ontvangst van de betaling van de voorgaande fase.

5.2 Doorlopende diensten (Module B) worden maandelijks vooraf gefactureerd.

5.3 Leads (Module C) worden per bundel vooraf gefactureerd. Levering start na ontvangst van de betaling.

5.4 De betaaltermijn is 14 dagen na factuurdatum. Opdrachtgever is niet gerechtigd tot opschorting of verrekening.

5.5 Bij overschrijding van de betaaltermijn is Opdrachtgever zonder ingebrekestelling in verzuim en is vanaf de vervaldag de wettelijke handelsrente (artikel 6:119a BW) verschuldigd. Daarnaast is Opdrachtgever de buitengerechtelijke incassokosten verschuldigd conform het Besluit vergoeding voor buitengerechtelijke incassokosten, met een minimum van € 40.

5.6 Zolang Opdrachtgever in verzuim is, mag AanloopAI de uitvoering van alle Overeenkomsten met Opdrachtgever opschorten, waaronder het leveren van Leads, het beheer en de hosting, zonder tot enige schadevergoeding gehouden te zijn.

5.7 Bezwaren tegen een factuur worden binnen 14 dagen na factuurdatum Schriftelijk en gemotiveerd gemeld. Daarna geldt de factuur als aanvaard. Een bezwaar schort de betalingsverplichting niet op.

### Artikel 6 — Uitvoering

6.1 AanloopAI voert de Overeenkomst naar beste inzicht en vermogen uit. Alle verplichtingen van AanloopAI zijn inspanningsverplichtingen, tenzij uitdrukkelijk Schriftelijk een resultaat is gegarandeerd.

6.2 AanloopAI garandeert geen bezoekersaantallen, posities in zoekmachines of AI-zoekdiensten, aantallen aanvragen of Leads, conversie, omzet of andere commerciële resultaten.

6.3 AanloopAI bepaalt de wijze van uitvoering en mag daarbij derden en AI-systemen inschakelen.

6.4 Overeengekomen termijnen zijn streefdata en geen fatale termijnen, tenzij Schriftelijk uitdrukkelijk anders is overeengekomen. Overschrijding van een termijn brengt AanloopAI niet in verzuim. Opdrachtgever dient AanloopAI in dat geval Schriftelijk in gebreke te stellen met een redelijke termijn van ten minste 14 dagen.

6.5 Termijnen schuiven op als Opdrachtgever zijn verplichtingen uit artikel 7 niet tijdig nakomt of als de omvang van de opdracht wijzigt.

### Artikel 7 — Verplichtingen van Opdrachtgever

7.1 Opdrachtgever verleent tijdig alle medewerking die redelijkerwijs nodig is voor de uitvoering en levert alle gevraagde gegevens, bestanden, teksten en toegangen aan via het Portaal binnen de daar aangegeven termijn.

7.2 Opdrachtgever staat in voor de juistheid, volledigheid en rechtmatigheid van het aangeleverde materiaal. Opdrachtgever garandeert dat hij gerechtigd is het materiaal te gebruiken en dat het geen inbreuk maakt op rechten van derden, en vrijwaart AanloopAI tegen aanspraken van derden op dit punt.

7.3 Opdrachtgever deelt geen wachtwoorden met AanloopAI. Toegang tot accounts (domein, analytics, bedrijfsprofielen, sociale media) wordt verleend door AanloopAI als gebruiker uit te nodigen op het eigen account van Opdrachtgever.

7.4 Opdrachtgever geeft binnen 5 werkdagen na voorlegging gemotiveerd Schriftelijk feedback op ontwerpen, teksten en opgeleverde onderdelen. Blijft feedback uit, dan geldt het onderdeel als goedgekeurd.

7.5 Opdrachtgever controleert door AanloopAI opgeleverde of door AI gegenereerde inhoud op feitelijke juistheid en op geschiktheid voor zijn bedrijf voordat deze wordt gepubliceerd of gebruikt.

7.6 De betalingsverplichtingen en de verplichtingen tot medewerking en informatieverstrekking gelden als essentiële verplichtingen van Opdrachtgever.

### Artikel 8 — Oplevering en acceptatie

8.1 AanloopAI meldt Schriftelijk wanneer een onderdeel of het geheel gereed is voor acceptatie.

8.2 Opdrachtgever test het opgeleverde binnen 5 werkdagen en meldt gebreken Schriftelijk en gespecificeerd. Gebreken die het gebruik niet wezenlijk belemmeren, staan acceptatie niet in de weg; AanloopAI herstelt deze binnen een redelijke termijn.

8.3 Het opgeleverde geldt als geaccepteerd als (a) Opdrachtgever dit Schriftelijk bevestigt, (b) de termijn van 8.2 verstrijkt zonder gespecificeerde melding, of (c) Opdrachtgever het opgeleverde in gebruik neemt.

### Artikel 9 — Intellectuele eigendom

9.1 Alle rechten van intellectuele eigendom op het Werk en op de door AanloopAI gebruikte of ontwikkelde methoden, generieke componenten, bibliotheken, templates, tooling, prompts, AI-agents, datasets, Platforms en knowhow berusten bij AanloopAI of haar licentiegevers.

9.2 In afwijking van 9.1 draagt AanloopAI, na volledige betaling van het eenmalige projectbedrag, de rechten op het **projectspecifieke Werk** over aan Opdrachtgever: het ontwerp, de teksten, de beelden die specifiek voor Opdrachtgever zijn gemaakt en de projectspecifieke broncode van de website. AanloopAI behoudt het recht de daaraan ten grondslag liggende algemene beginselen, ideeën, structuren en programmeertechnieken te blijven gebruiken.

9.3 Op generieke componenten die onderdeel zijn van het opgeleverde Werk verkrijgt Opdrachtgever een niet-exclusief, niet-overdraagbaar en eeuwigdurend gebruiksrecht, uitsluitend voor het gebruik van het betreffende Werk.

9.4 Door AI gegenereerd beeld- en tekstmateriaal wordt geleverd in de staat waarin het verkeert. AanloopAI garandeert geen exclusiviteit en kan niet garanderen dat op dit materiaal auteursrecht ontstaat.

9.5 AanloopAI mag het Werk, de naam en het logo van Opdrachtgever gebruiken als referentie in haar portfolio en uitingen, tenzij Opdrachtgever hiertegen Schriftelijk bezwaar maakt. AanloopAI mag een bescheiden vermelding ("Website door AanloopAI") in de voettekst van de website plaatsen.

9.6 Opdrachtgever verwijdert geen aanduidingen van rechthebbenden uit het Werk.

### Artikel 10 — Gebruik van AI-systemen

10.1 AanloopAI zet AI-systemen in bij het maken van teksten, beelden en code en bij de werking van AI-agents die namens Opdrachtgever communiceren.

10.2 Waar een AI-agent met eindgebruikers communiceert, zorgt AanloopAI dat dit als zodanig kenbaar is, conform de transparantieverplichtingen van Verordening (EU) 2024/1689 (AI-verordening).

10.3 AanloopAI is niet aansprakelijk voor door AI gegenereerde inhoud die Opdrachtgever heeft goedgekeurd of in gebruik heeft genomen, noch voor beslissingen die Opdrachtgever of derden op basis daarvan nemen.

10.4 Opdrachtgever gebruikt AI-agents van AanloopAI niet voor doeleinden die in strijd zijn met de wet of met de gebruiksvoorwaarden van de onderliggende AI-aanbieders.

### Artikel 11 — Portaal en elektronische ondertekening

11.1 Opdrachtgever krijgt toegang tot het Portaal via persoonlijke inloggegevens of eenmalige inloglinks. Opdrachtgever houdt deze geheim en is verantwoordelijk voor al het gebruik via zijn account.

11.2 Documenten worden in het Portaal gelezen en ondertekend door middel van een elektronische handtekening (artikel 3:15a BW; Verordening (EU) nr. 910/2014). Partijen komen overeen dat deze handtekening dezelfde rechtsgevolgen heeft als een handgeschreven handtekening.

11.3 De door het Portaal vastgelegde gegevens — waaronder tijdstippen van openen, scrollen en bevestigen, IP-adres, browsergegevens, de getypte naam, de handtekeningafbeelding, de verificatiecode en de cryptografische controlesommen van de documenten — gelden tussen partijen als dwingend bewijs van de inhoud en ondertekening van het document, behoudens tegenbewijs.

11.4 Meldingen van Opdrachtgever die volgens de Overeenkomst via het Portaal moeten worden gedaan (zoals het melden van een ongeldige Lead), zijn alleen geldig als zij via het Portaal zijn gedaan.

### Artikel 12 — Geheimhouding

12.1 Partijen houden alle informatie van de ander waarvan zij weten of redelijkerwijs behoren te weten dat deze vertrouwelijk is, geheim, ook na afloop van de Overeenkomst.

12.2 Deze verplichting geldt niet voor informatie die openbaar is, die een partij al rechtmatig bezat, of die op grond van een wettelijke plicht of rechterlijk bevel moet worden verstrekt.

### Artikel 13 — Persoonsgegevens

13.1 Voor zover AanloopAI bij de uitvoering persoonsgegevens verwerkt ten behoeve van Opdrachtgever, gelden de Privacyverklaring en de Verwerkersovereenkomst van AanloopAI, die onderdeel zijn van de Overeenkomst.

13.2 Voor Leads geldt de rolverdeling uit Module C en de Verwerkersovereenkomst: AanloopAI en Opdrachtgever zijn ieder zelfstandig verwerkingsverantwoordelijke.

### Artikel 14 — Aansprakelijkheid

14.1 De totale aansprakelijkheid van AanloopAI wegens een toerekenbare tekortkoming, onrechtmatige daad of enige andere grond is beperkt tot vergoeding van **directe schade** tot maximaal het bedrag (exclusief btw) dat Opdrachtgever in de **twaalf maanden** voorafgaand aan de schadeveroorzakende gebeurtenis onder de betreffende Overeenkomst aan AanloopAI heeft betaald, met een maximum van **€ 10.000** per gebeurtenis en per kalenderjaar. Een reeks samenhangende gebeurtenissen geldt als één gebeurtenis.

14.2 Onder directe schade wordt uitsluitend verstaan: (a) redelijke kosten om de prestatie van AanloopAI aan de Overeenkomst te laten beantwoorden, (b) redelijke kosten ter vaststelling van oorzaak en omvang van de schade, en (c) redelijke kosten ter voorkoming of beperking van schade, voor zover Opdrachtgever aantoont dat deze kosten tot beperking hebben geleid.

14.3 Aansprakelijkheid voor **indirecte schade** is uitgesloten, waaronder gevolgschade, gederfde winst of omzet, gemiste besparingen, gemiste Leads of opdrachten, reputatieschade, bedrijfsstagnatie, en verlies, beschadiging of verminking van gegevens.

14.4 AanloopAI is niet aansprakelijk voor schade die het gevolg is van (a) storingen, wijzigingen of beleid van derden zoals hosting-, DNS-, e-mail- en AI-aanbieders, Google, Meta en WhatsApp, (b) door Opdrachtgever aangeleverd materiaal of verstrekte informatie, (c) wijzigingen die Opdrachtgever of derden zonder AanloopAI in het Werk hebben aangebracht, of (d) het handelen van personen die via een Lead met Opdrachtgever in contact zijn gekomen.

14.5 De beperkingen in dit artikel gelden niet voor zover de schade het gevolg is van opzet of bewuste roekeloosheid van AanloopAI.

14.6 Aansprakelijkheid ontstaat alleen als Opdrachtgever AanloopAI onverwijld en deugdelijk Schriftelijk in gebreke stelt, met een redelijke termijn voor herstel, en AanloopAI ook na die termijn toerekenbaar tekort blijft schieten.

14.7 Iedere vordering tot schadevergoeding vervalt door verloop van **twaalf maanden** na het ontstaan ervan, tenzij Opdrachtgever binnen die termijn een rechtsvordering heeft ingesteld.

14.8 Opdrachtgever vrijwaart AanloopAI tegen aanspraken van derden die verband houden met het gebruik van het Werk of van Leads door Opdrachtgever.

### Artikel 15 — Overmacht

15.1 Geen van partijen is gehouden tot nakoming van een verplichting als zij daartoe verhinderd is door overmacht. Onder overmacht wordt mede verstaan: storingen of uitval van hosting-, netwerk-, e-mail- en AI-diensten van derden, cyberaanvallen, wijzigingen in beleid of API''s van platforms zoals Google, Meta en WhatsApp, overheidsmaatregelen, ziekte, stakingen en oorlog.

15.2 Duurt de overmacht langer dan 60 dagen, dan mogen beide partijen de Overeenkomst voor het niet-uitgevoerde deel Schriftelijk ontbinden, zonder schadeplichtig te zijn. Reeds verrichte prestaties worden naar verhouding afgerekend.

### Artikel 16 — Duur, opzegging en ontbinding

16.1 Een Overeenkomst voor een eenmalig project eindigt met de oplevering en volledige betaling. Opdrachtgever kan een eenmalig project niet tussentijds opzeggen; wil hij toch stoppen, dan blijven de tot dan verrichte werkzaamheden en de lopende fase volledig verschuldigd.

16.2 Doorlopende diensten worden aangegaan voor onbepaalde tijd en zijn door beide partijen Schriftelijk opzegbaar tegen het einde van een kalendermaand, met inachtneming van een opzegtermijn van één kalendermaand.

16.3 Ieder van partijen mag de Overeenkomst met onmiddellijke ingang Schriftelijk ontbinden als de ander (a) in staat van faillissement wordt verklaard of surseance van betaling aanvraagt, (b) zijn onderneming staakt of liquideert, of (c) na deugdelijke ingebrekestelling een essentiële verplichting niet nakomt.

16.4 Bij ontbinding blijven de door AanloopAI verrichte prestaties en de daarmee samenhangende betalingsverplichtingen in stand en zijn deze niet onderwerp van ongedaanmaking. Vooruitbetaalde bedragen voor nog niet geleverde prestaties worden alleen gerestitueerd als de ontbinding niet aan Opdrachtgever is toe te rekenen.

16.5 Na het einde van een Overeenkomst voor beheer of hosting verleent AanloopAI gedurende 30 dagen redelijke medewerking aan de overdracht van de website en de bijbehorende gegevens aan Opdrachtgever of een door hem aangewezen partij. Daarna mag AanloopAI de gegevens verwijderen.

### Artikel 17 — Overdracht

17.1 Opdrachtgever mag rechten en verplichtingen uit de Overeenkomst niet zonder Schriftelijke toestemming van AanloopAI aan een derde overdragen.

17.2 AanloopAI mag de Overeenkomst of onderdelen daarvan overdragen aan een rechtsopvolger of een door haar gecontroleerde vennootschap, en informeert Opdrachtgever daarover.

### Artikel 18 — Wijziging van deze voorwaarden

18.1 AanloopAI mag deze voorwaarden wijzigen. Wijzigingen worden ten minste één maand vóór inwerkingtreding Schriftelijk of via het Portaal aangekondigd.

18.2 Accepteert Opdrachtgever een wijziging die zijn positie wezenlijk verslechtert niet, dan mag hij de doorlopende diensten tegen de ingangsdatum van de wijziging opzeggen.

18.3 Op een eenmalig project blijft de versie van toepassing die gold bij totstandkoming van die Overeenkomst.

### Artikel 19 — Klachten

19.1 Klachten over de uitvoering meldt Opdrachtgever zo spoedig mogelijk, maar uiterlijk binnen 14 dagen na ontdekking, Schriftelijk en gemotiveerd aan AanloopAI.

19.2 AanloopAI reageert binnen 10 werkdagen inhoudelijk op de klacht.

### Artikel 20 — Toepasselijk recht en geschillen

20.1 Op alle rechtsverhoudingen tussen AanloopAI en Opdrachtgever is Nederlands recht van toepassing.

20.2 Partijen spannen zich in geschillen eerst in onderling overleg op te lossen. Lukt dat niet binnen 30 dagen na de eerste Schriftelijke melding van het geschil, dan is de rechtbank Rotterdam exclusief bevoegd, tenzij dwingend recht anders bepaalt.

---

## MODULE A — WEBSITES EN ONTWIKKELING

### Artikel A1 — Omvang

A1.1 De omvang van het Werk is beschreven in de Overeenkomst. Niet genoemde onderdelen vallen buiten de opdracht.

A1.2 Teksten komen tot stand in samenwerking: Opdrachtgever levert de inhoudelijke input, AanloopAI schrijft en redigeert. Beeldmateriaal dat Opdrachtgever niet aanlevert, maakt AanloopAI met AI-tools of stockmateriaal.

A1.3 Standaard wordt één ontwerpronde met één correctieronde geleverd. Extra rondes zijn meerwerk.

### Artikel A2 — Hosting en domein

A2.1 Het domein staat op naam van Opdrachtgever. AanloopAI koppelt het domein en beheert DNS en hosting op basis van de door Opdrachtgever verleende toegang.

A2.2 Hosting is inbegrepen zolang een beheerovereenkomst (Module B) loopt. Zonder beheerovereenkomst draagt AanloopAI de website na oplevering over aan een hostingomgeving van Opdrachtgever, of levert hosting tegen een apart overeengekomen tarief.

A2.3 AanloopAI streeft naar een beschikbaarheid van 99,5% per maand, gemeten over de door AanloopAI beheerde omgeving en met uitzondering van aangekondigd onderhoud en storingen bij derden.

### Artikel A3 — Garantie

A3.1 AanloopAI herstelt gedurende 30 dagen na acceptatie kosteloos reproduceerbare gebreken die aan haar toerekenbaar zijn. Deze garantie vervalt als Opdrachtgever of een derde zonder toestemming van AanloopAI wijzigingen heeft aangebracht in het Werk.

A3.2 Gebreken als gevolg van wijzigingen in browsers, besturingssystemen, API''s of diensten van derden vallen niet onder de garantie.

### Artikel A4 — Juridische teksten op de website

A4.1 AanloopAI levert een concept-privacyverklaring en cookiebeleid voor de website van Opdrachtgever. Opdrachtgever blijft als verwerkingsverantwoordelijke zelf verantwoordelijk voor de juistheid en volledigheid daarvan en voor de naleving van de AVG op zijn website.

---

## MODULE B — BEHEER EN DOORLOPENDE DIENSTEN

### Artikel B1 — Inhoud

B1.1 Beheer omvat de in de Overeenkomst vermelde doorlopende werkzaamheden gericht op het laten groeien van de leadstroom van de website, zoals zoekmachineoptimalisatie, het toevoegen van lokale en inhoudelijke pagina''s, conversieverbeteringen, beheer van het Google Bedrijfsprofiel, geautomatiseerde reviewverzoeken, maandrapportage, hosting, back-ups, updates en technisch onderhoud.

B1.2 AanloopAI bepaalt op basis van de cijfers welke werkzaamheden in een maand prioriteit krijgen en legt dit vast in de maandrapportage.

B1.3 **AanloopAI voert geen betaalde advertentiecampagnes uit (zoals Google Ads of Meta Ads), beheert geen advertentiebudgetten en adviseert daar niet over.**

### Artikel B2 — Looptijd en facturatie

B2.1 Beheer gaat in bij livegang van de website of op de in de Overeenkomst genoemde datum, wordt aangegaan voor onbepaalde tijd en wordt maandelijks vooraf gefactureerd.

B2.2 Opzegging geschiedt conform artikel 16.2.

B2.3 Werkzaamheden buiten de omvang van B1.1, zoals nieuwe functionaliteit, herontwerp of campagnepagina''s buiten het plan, zijn meerwerk.

### Artikel B3 — Toegangen en gegevens

B3.1 Opdrachtgever houdt de verleende toegangen (artikel 7.3) in stand voor de duur van het beheer. Intrekking van toegang ontslaat AanloopAI van de daarvan afhankelijke verplichtingen zonder dat de vergoeding vervalt.

B3.2 Rapportages en analysegegevens blijven voor Opdrachtgever beschikbaar tot 30 dagen na het einde van het beheer.

---

## MODULE C — LEADS

### Artikel C1 — Aard van de dienst

C1.1 AanloopAI levert Leads die via een Platform binnenkomen en voldoen aan de in de Overeenkomst vastgelegde criteria: product of dienst, regio en maximumaantal per dag.

C1.2 AanloopAI garandeert geen minimumaantal Leads per dag, week of maand. De instroom hangt af van het zoekgedrag van consumenten en bedrijven.

C1.3 Een Lead is een aanvraag om contact, een offerte of een afspraak. AanloopAI garandeert niet dat de Lead tot een afspraak of opdracht leidt.

### Artikel C2 — Exclusiviteit

C2.1 Tenzij anders overeengekomen zijn Leads exclusief: AanloopAI levert dezelfde Lead niet aan een andere afnemer.

C2.2 Exclusiviteit ziet alleen op de levering door AanloopAI. Het staat de aanvrager vrij zelf ook elders aanvragen te doen.

### Artikel C3 — Levering en opvolging

C3.1 Leads worden direct na binnenkomst en controle geleverd per e-mail en WhatsApp aan het door Opdrachtgever opgegeven contact, en zijn zichtbaar in het Portaal.

C3.2 Opdrachtgever neemt binnen één werkdag na levering contact op met de aanvrager. Snelle opvolging is bepalend voor conversie; het structureel uitblijven van opvolging geeft AanloopAI het recht de levering te pauzeren en aan te passen.

C3.3 Opdrachtgever informeert de aanvrager bij het eerste contact over zijn identiteit en over de herkomst van de aanvraag (het Platform).

### Artikel C4 — Bundels en betaling

C4.1 Leads worden afgenomen in bundels van het in de Overeenkomst genoemde aantal en worden vooraf gefactureerd. Levering van een bundel start na ontvangst van de betaling.

C4.2 Een bundel is 12 maanden geldig vanaf de factuurdatum. Niet-afgenomen Leads vervallen daarna zonder restitutie.

C4.3 Opdrachtgever kan de levering via het Portaal op ieder moment pauzeren en hervatten. Pauzeren verlengt de geldigheid van de bundel niet.

C4.4 Is een bundel bijna op, dan informeert AanloopAI Opdrachtgever. Wordt geen nieuwe bundel afgenomen, dan stopt de levering na de laatste Lead van de bundel.

### Artikel C5 — Ongeldige Leads en vervanging

C5.1 Een Lead is **ongeldig** als:
(a) het telefoonnummer én het e-mailadres aantoonbaar onjuist zijn of niet bestaan;
(b) de aanvrager onbereikbaar is, mits Opdrachtgever ten minste drie belpogingen op verschillende dagen en tijdstippen én één schriftelijke poging (e-mail of WhatsApp) heeft gedaan en dit met data en tijdstippen vastlegt;
(c) het een dubbele aanvraag van dezelfde aanvrager betreft die binnen 30 dagen eerder door AanloopAI aan Opdrachtgever is geleverd;
(d) het adres van de aanvrager buiten de overeengekomen regio ligt;
(e) de aanvraag geen betrekking heeft op het overeengekomen product of de overeengekomen dienst;
(f) de aanvrager ontkent de aanvraag te hebben gedaan of toestemming te hebben gegeven.

C5.2 **Niet ongeldig** is een Lead waarbij de aanvrager (a) geen afspraak of opdracht wil, (b) zijn aanvraag intrekt of uitstelt, (c) voor een andere aanbieder kiest, (d) een ander budget heeft dan Opdrachtgever wenst, of (e) al bij Opdrachtgever bekend was zonder dat sprake is van C5.1 onder c.

C5.3 Opdrachtgever meldt een ongeldige Lead **via het Portaal**, met opgave van de reden en het bewijs, binnen **2 werkdagen** na levering voor de gronden a, c, d, e en f, en binnen **5 werkdagen** na levering voor grond b (onbereikbaarheid). Niet of te laat gemelde Leads gelden als geldig.

C5.4 Per kalendermaand kan maximaal 10% van de in die maand geleverde Leads wegens onbereikbaarheid (grond b) worden gemeld. Voor de overige gronden geldt geen maximum.

C5.5 AanloopAI beoordeelt de melding binnen 5 werkdagen. Is de melding gegrond, dan wordt de Lead niet op de bundel in mindering gebracht, of wordt een vervangende Lead geleverd. **Er vindt geen terugbetaling in geld plaats.**

C5.6 Bij een verschil van inzicht over de geldigheid is het oordeel van AanloopAI, gebaseerd op de in het Platform vastgelegde gegevens en het door Opdrachtgever geleverde bewijs, beslissend, behoudens tegenbewijs door Opdrachtgever.

### Artikel C6 — Gebruik van Leads en persoonsgegevens

C6.1 Opdrachtgever gebruikt een Lead uitsluitend om de aanvraag van de betreffende aanvrager te beantwoorden en voor de daaruit voortvloeiende klantrelatie.

C6.2 Het is Opdrachtgever niet toegestaan Leads door te verkopen, door te leveren, te delen met derden, op te nemen in marketinglijsten of nieuwsbrieven zonder eigen toestemming van de aanvrager, of voor andere doeleinden te gebruiken.

C6.3 Vanaf levering is Opdrachtgever zelfstandig verwerkingsverantwoordelijke voor de verdere verwerking van de Lead. Opdrachtgever beveiligt de gegevens passend, beperkt de toegang tot medewerkers die de Lead opvolgen, respecteert bezwaar en intrekking van toestemming onmiddellijk, en verwijdert de gegevens uiterlijk 12 maanden na levering als geen klantrelatie is ontstaan.

C6.4 Opdrachtgever meldt een datalek dat Leadgegevens raakt binnen 48 uur na ontdekking aan AanloopAI.

C6.5 Opdrachtgever vrijwaart AanloopAI tegen aanspraken van aanvragers of toezichthouders die voortvloeien uit het gebruik van Leads door Opdrachtgever in strijd met dit artikel of de wet.

### Artikel C7 — Beëindiging

C7.1 Bij beëindiging van de Overeenkomst om welke reden ook, vervallen niet-afgenomen Leads uit lopende bundels zonder restitutie, tenzij de beëindiging het gevolg is van een toerekenbare tekortkoming van AanloopAI.

C7.2 AanloopAI mag de levering van Leads met onmiddellijke ingang beëindigen als Opdrachtgever handelt in strijd met artikel C6, structureel klachten van aanvragers oplevert, of in verzuim is met betaling.

---

*Einde Algemene Voorwaarden AanloopAI, versie 1.0.*
', 1760000000000, 1760000000000);
INSERT OR IGNORE INTO agr_templates (id, slug, version, title, body_markdown, effective_from, created_at) VALUES ('tpl_privacy_1_0', 'privacy-verwerker', '1.0', 'Privacyverklaring en Verwerkersovereenkomst', '# Privacyverklaring AanloopAI

**Versie 1.0 — 9 oktober 2026**

## 1. Wie wij zijn

AanloopAI is een handelsnaam van Mustafa Dogan, Blokfluit 31, 3068 KZ Rotterdam, KvK 88606902. AanloopAI is verwerkingsverantwoordelijke voor de verwerkingen die in deze verklaring worden beschreven. Contactpersoon voor privacy: Mustafa Dogan, m.dogan@aanloopai.nl. AanloopAI heeft geen functionaris voor gegevensbescherming; dat is voor onze omvang en verwerkingen niet verplicht.

Deze verklaring geldt voor aanloopai.nl, het klantenportaal "Mijn AanloopAI", onze leadplatforms (waaronder keukeninbeeld.nl en zoekeen.nl), onze AI-agents (chat, spraak en WhatsApp) en ons contact met opdrachtgevers en relaties.

## 2. Welke gegevens wij verwerken, waarom en hoe lang

| Van wie | Gegevens | Doel | Grondslag (AVG) | Bewaartermijn |
|---|---|---|---|---|
| Opdrachtgevers en contactpersonen | Naam, functie, bedrijfsnaam, KvK- en btw-nummer, adres, e-mail, telefoon, bankgegevens voor facturatie, correspondentie | Voorstel, uitvoering en administratie van de overeenkomst, facturatie, contact | Art. 6 lid 1 sub b (overeenkomst); sub c (fiscale bewaarplicht) | 7 jaar na einde boekjaar waarin de overeenkomst eindigde |
| Gebruikers van het Portaal | E-mailadres, naam, inlogtijdstippen, eenmalige inlogcodes (gehasht), sessiegegevens | Toegang geven tot het Portaal, beveiliging, misbruik voorkomen | Art. 6 lid 1 sub b; sub f (beveiliging) | Duur van de overeenkomst + 1 jaar; inloglogs 12 maanden |
| Ondertekenaars in het Portaal | Getypte naam, handtekeningafbeelding, tijdstippen van openen, scrollen en bevestigen, IP-adres, browser- en apparaatgegevens, verificatiecode per e-mail, controlesommen van documenten | Bewijs dat en door wie een document is gelezen en ondertekend | Art. 6 lid 1 sub b; sub f (bewijsbelang van beide partijen) | 7 jaar na einde van de overeenkomst waarop de ondertekening ziet |
| Opdrachtgevers (aanlevering) | Logo''s, foto''s, teksten, toegangsgegevens tot eigen accounts (geen wachtwoorden), overige bestanden; foto''s kunnen afbeeldingen van medewerkers of klanten van opdrachtgever bevatten | Uitvoering van het project | Art. 6 lid 1 sub b | 2 jaar na einde van de overeenkomst, daarna verwijdering; opdrachtgever kan eerder om verwijdering vragen |
| Aanvragers op onze leadplatforms | Naam, e-mail, telefoon, postcode en plaats (soms adres), omschrijving van de aanvraag, voorkeuren, tijdstip, IP-adres, herkomst (pagina/campagne) | De aanvraag beoordelen en doorgeven aan één passende ondernemer in de regio; de aanvrager en ondernemer in contact brengen; misbruik en dubbele aanvragen voorkomen | Art. 6 lid 1 sub a (toestemming, gegeven bij de aanvraag); sub f (fraudepreventie, bewijs van toestemming) | 12 maanden na de aanvraag; bewijs van toestemming 3 jaar |
| Gebruikers van AI-agents (chat, spraak, WhatsApp) | Inhoud van het gesprek, telefoonnummer of WhatsApp-nummer, tijdstip, eventueel door de gebruiker gedeelde contactgegevens | De vraag beantwoorden, doorverwijzen, een afspraak of terugbelverzoek vastleggen, de agent verbeteren | Art. 6 lid 1 sub a (toestemming bij start van het gesprek); sub f (verbetering van de dienst) | Gespreksinhoud 6 maanden; spraakopnames worden niet bewaard na transcriptie, tenzij de gebruiker daarom vraagt |
| Websitebezoekers | Geanonimiseerd IP-adres, pagina''s, apparaat, browser, verwijzende site | Statistiek en verbetering van de website | Art. 6 lid 1 sub f (analytische cookies alleen na toestemming, art. 11.7a Telecommunicatiewet) | 26 maanden |
| Sollicitanten en zakelijke relaties | Naam, contactgegevens, cv, correspondentie | Werving, relatiebeheer | Art. 6 lid 1 sub b en f | Sollicitanten 4 weken na afwijzing (met toestemming 1 jaar); relaties zolang de relatie actief is |

Wij verwerken geen bijzondere categorieën persoonsgegevens (zoals gezondheid of religie) en vragen daar niet om. Deelt een gebruiker die toch met ons, bijvoorbeeld in een gesprek met een AI-agent, dan verwerken wij die alleen voor zover nodig om de vraag te beantwoorden en verwijderen wij ze zo snel mogelijk.

## 3. Hoe wij aan gegevens komen

Gegevens van opdrachtgevers krijgen wij van henzelf. Gegevens van aanvragers krijgen wij via het formulier of de AI-agent waarmee zij hun aanvraag doen. Wij kopen geen adresbestanden en verrijken gegevens niet uit externe bronnen, met uitzondering van openbare bedrijfsgegevens uit het Handelsregister voor de administratie van opdrachtgevers.

## 4. Met wie wij gegevens delen

Wij delen persoonsgegevens alleen als dat nodig is voor onze dienstverlening of op grond van een wettelijke plicht.

**Ontvangers van leadgegevens.** Een aanvraag op een leadplatform geven wij door aan **één** aangesloten ondernemer die past bij het product en de regio van de aanvrager. Die ondernemer wordt vanaf ontvangst zelf verwerkingsverantwoordelijke voor zijn contact met de aanvrager en is daar ook zelf op aanspreekbaar. Welke ondernemer dat is, melden wij de aanvrager bij de bevestiging van de aanvraag. Wij verkopen leadgegevens niet aan meerdere partijen en niet aan adreshandelaren.

**Verwerkers.** Wij gebruiken de volgende categorieën dienstverleners, die gegevens alleen in onze opdracht verwerken en met wie wij verwerkersovereenkomsten hebben gesloten:

| Categorie | Dienstverlener(s) | Locatie verwerking |
|---|---|---|
| Hosting en infrastructuur | Hetzner Online GmbH (Duitsland/Finland), Cloudflare (CDN, DNS, beveiliging) | EU; Cloudflare wereldwijd met EU-datalokalisatie waar beschikbaar |
| E-mail | mijn.host (Nederland), Brevo (Frankrijk) | EU |
| AI-modellen en spraak | ElevenLabs (spraakagents), Anthropic en OpenAI (taalmodellen) | VS; op basis van EU-standaardcontractbepalingen en, waar van toepassing, het EU-VS Data Privacy Framework. Gespreksinhoud wordt door deze aanbieders niet gebruikt voor training van hun modellen (zakelijke voorwaarden). |
| Berichten | Meta Platforms Ireland (WhatsApp Business), Telegram (uitsluitend interne notificaties aan AanloopAI zonder volledige persoonsgegevens) | Ierland/EU; Telegram buiten EU, zonder persoonsgegevens |
| Statistiek | Google Analytics 4 met IP-anonimisering en gegevensdeling uitgeschakeld, of een privacyvriendelijk alternatief | EU/VS (DPF) |
| Administratie | Boekhoud- en facturatiesoftware van AanloopAI | EU |

De actuele lijst van verwerkers staat in Bijlage 2 bij de Verwerkersovereenkomst en wordt bij wijziging bijgewerkt.

**Overige ontvangers.** Accountant of boekhouder (fiscale administratie), bank (betalingen), en overheidsinstanties voor zover wij daartoe wettelijk verplicht zijn.

## 5. Doorgifte buiten de EER

Sommige van onze dienstverleners verwerken gegevens in de Verenigde Staten. Dat gebeurt uitsluitend op basis van een adequaatheidsbesluit van de Europese Commissie (het EU-VS Data Privacy Framework, voor gecertificeerde ontvangers) of de door de Commissie vastgestelde standaardcontractbepalingen (uitvoeringsbesluit (EU) 2021/914), aangevuld met versleuteling en pseudonimisering waar mogelijk. Een kopie van de gebruikte waarborgen kunt u bij ons opvragen.

## 6. Hoe wij gegevens beveiligen

Wij nemen passende technische en organisatorische maatregelen, waaronder: versleutelde verbindingen (TLS 1.2 of hoger), versleutelde opslag van back-ups, toegang op basis van persoonlijke accounts en tweefactorauthenticatie, het principe van minimale toegang, logging van toegang tot het Portaal, dagelijkse back-ups, tijdige beveiligingsupdates en afgeschermde opslag van geüploade bestanden zonder publieke links. Een uitgebreider overzicht staat in Bijlage 3 bij de Verwerkersovereenkomst.

## 7. Geautomatiseerde besluitvorming en AI

Onze AI-agents beantwoorden vragen en leggen aanvragen vast; zij nemen geen besluiten met rechtsgevolgen voor u en maken geen profielen van u. Bij het begin van een gesprek maken wij kenbaar dat u met een AI-systeem spreekt. U kunt altijd vragen om contact met een mens. De toewijzing van een aanvraag aan een ondernemer gebeurt op basis van product en regio en wordt door AanloopAI gecontroleerd.

## 8. Cookies

aanloopai.nl en onze platforms plaatsen functionele cookies die nodig zijn voor de werking van de site (zoals sessiecookies in het Portaal). Analytische en marketingcookies plaatsen wij alleen na uw toestemming via de cookiebanner. U kunt uw keuze op elk moment aanpassen via de link "Cookie-instellingen" onderaan de website. Een overzicht van de gebruikte cookies staat in ons cookiebeleid.

## 9. Uw rechten

U heeft het recht op inzage, rectificatie, verwijdering, beperking van de verwerking, overdraagbaarheid van uw gegevens en bezwaar tegen verwerking op grond van gerechtvaardigd belang. Heeft u toestemming gegeven, dan kunt u die op elk moment intrekken; dat tast de rechtmatigheid van de verwerking vóór de intrekking niet aan. Als aanvrager op een leadplatform kunt u ook bij de ondernemer die uw aanvraag heeft ontvangen uw rechten uitoefenen.

Stuur uw verzoek naar m.dogan@aanloopai.nl. Wij kunnen u vragen zich te identificeren. Wij reageren binnen één maand; bij complexe verzoeken kunnen wij die termijn met twee maanden verlengen en laten wij u dat weten.

Bent u niet tevreden over hoe wij met uw gegevens omgaan, dan horen wij dat graag. U heeft daarnaast altijd het recht een klacht in te dienen bij de Autoriteit Persoonsgegevens (autoriteitpersoonsgegevens.nl).

## 10. Wijzigingen

Wij kunnen deze verklaring aanpassen, bijvoorbeeld bij nieuwe diensten of dienstverleners. De actuele versie staat op aanloopai.nl/privacy en in het Portaal. Bij wezenlijke wijzigingen informeren wij opdrachtgevers via het Portaal of per e-mail.

---
---

# Verwerkersovereenkomst

Deze Verwerkersovereenkomst maakt onlosmakelijk deel uit van de Overeenkomst met referentie **{{agreement_id}}** tussen:

1. **{{klant_bedrijfsnaam}}**, gevestigd te {{klant_adres}}, {{klant_postcode}} {{klant_plaats}}, KvK {{klant_kvk}}, hierna **"Verwerkingsverantwoordelijke"** of **"Opdrachtgever"**; en

2. **AanloopAI**, handelsnaam van Mustafa Dogan, Blokfluit 31, 3068 KZ Rotterdam, KvK 88606902, hierna **"Verwerker"** of **"AanloopAI"**.

Begrippen uit de Algemene Verordening Gegevensbescherming (Verordening (EU) 2016/679, "AVG") hebben in deze overeenkomst dezelfde betekenis als in de AVG.

## Artikel 1 — Rolverdeling

1.1 **Verwerking voor Opdrachtgever (deel I van deze overeenkomst).** Bij het bouwen, hosten en beheren van de website {{project_domein}}, de daarop geplaatste formulieren en afspraakmodule, de analytics en eventuele AI-agents die namens Opdrachtgever communiceren, verwerkt AanloopAI persoonsgegevens van bezoekers en klanten van Opdrachtgever **in opdracht van** Opdrachtgever. Opdrachtgever is verwerkingsverantwoordelijke; AanloopAI is verwerker in de zin van artikel 28 AVG.

1.2 **Leads (deel II van deze overeenkomst).** Aanvragen die binnenkomen via een Platform van AanloopAI (zoals keukeninbeeld.nl) verzamelt AanloopAI onder eigen verantwoordelijkheid, met toestemming van de aanvrager, en geeft AanloopAI door aan Opdrachtgever. Voor dit deel zijn AanloopAI en Opdrachtgever **ieder zelfstandig verwerkingsverantwoordelijke**: AanloopAI voor het verzamelen, controleren en doorgeven; Opdrachtgever voor alles wat hij na ontvangst met de gegevens doet. Deel I is op deze gegevens niet van toepassing; deel II wel.

---

## DEEL I — AANLOOPAI ALS VERWERKER

### Artikel 2 — Onderwerp, aard en doel

2.1 AanloopAI verwerkt de in **Bijlage 1** omschreven categorieën persoonsgegevens van de daar genoemde categorieën betrokkenen, uitsluitend voor de daar genoemde doeleinden en voor de duur van de Overeenkomst.

2.2 AanloopAI verwerkt de persoonsgegevens uitsluitend op basis van schriftelijke instructies van Opdrachtgever. De Overeenkomst, deze Verwerkersovereenkomst en de via het Portaal gegeven instructies gelden als die instructies. Verplicht Unierecht of Nederlands recht AanloopAI tot een andere verwerking, dan stelt AanloopAI Opdrachtgever daarvan vooraf op de hoogte, tenzij de wet dat verbiedt.

2.3 AanloopAI gebruikt de persoonsgegevens niet voor eigen doeleinden, verkoopt ze niet en gebruikt ze niet om AI-modellen te trainen.

2.4 Acht AanloopAI een instructie in strijd met de AVG of andere privacywetgeving, dan meldt zij dat onverwijld aan Opdrachtgever en mag zij de uitvoering opschorten tot de instructie is aangepast of bevestigd.

### Artikel 3 — Verplichtingen van Opdrachtgever

3.1 Opdrachtgever staat ervoor in dat hij een geldige grondslag heeft voor de verwerking, dat betrokkenen correct zijn geïnformeerd (onder meer via een privacyverklaring op {{project_domein}}, waarvoor AanloopAI een concept levert) en dat de instructies aan AanloopAI rechtmatig zijn.

3.2 Opdrachtgever is verantwoordelijk voor het beheer van de eigen accounts (domein, analytics, bedrijfsprofiel, agenda) en voor het tijdig intrekken van toegangen van eigen medewerkers die het bedrijf verlaten.

3.3 Opdrachtgever vrijwaart AanloopAI tegen aanspraken van betrokkenen en toezichthouders die het gevolg zijn van het ontbreken van een grondslag, onjuiste informatievoorziening aan betrokkenen of onrechtmatige instructies.

### Artikel 4 — Vertrouwelijkheid

4.1 AanloopAI houdt de persoonsgegevens geheim en verplicht alle personen die onder haar gezag persoonsgegevens verwerken tot geheimhouding, tenzij een wettelijke plicht tot bekendmaking bestaat.

4.2 Deze verplichting blijft na het einde van de Overeenkomst bestaan.

### Artikel 5 — Beveiliging

5.1 AanloopAI neemt de in **Bijlage 3** beschreven technische en organisatorische maatregelen, rekening houdend met de stand van de techniek, de uitvoeringskosten en de aard, omvang, context en doeleinden van de verwerking en de risico''s voor betrokkenen (artikel 32 AVG).

5.2 AanloopAI mag de maatregelen aanpassen, mits het beveiligingsniveau niet daalt. Wezenlijke wijzigingen worden in Bijlage 3 vastgelegd en via het Portaal gemeld.

### Artikel 6 — Subverwerkers

6.1 Opdrachtgever geeft AanloopAI algemene toestemming om subverwerkers in te schakelen. De bij ondertekening ingeschakelde subverwerkers staan in **Bijlage 2**.

6.2 AanloopAI informeert Opdrachtgever via het Portaal of per e-mail ten minste **14 dagen** voordat een nieuwe subverwerker wordt ingeschakeld of een bestaande wordt vervangen. Maakt Opdrachtgever binnen die termijn gemotiveerd en schriftelijk bezwaar, dan treden partijen in overleg. Komen zij er niet uit, dan mag Opdrachtgever het betreffende onderdeel van de Overeenkomst opzeggen tegen de datum waarop de wijziging ingaat, zonder dat AanloopAI tot schadevergoeding gehouden is.

6.3 AanloopAI legt aan iedere subverwerker schriftelijk verplichtingen op die ten minste gelijkwaardig zijn aan die in deze Verwerkersovereenkomst, in het bijzonder op het gebied van beveiliging en vertrouwelijkheid.

6.4 AanloopAI blijft jegens Opdrachtgever volledig aansprakelijk voor de nakoming van de verplichtingen door haar subverwerkers.

### Artikel 7 — Doorgifte buiten de EER

7.1 AanloopAI verwerkt persoonsgegevens binnen de Europese Economische Ruimte, met uitzondering van de in Bijlage 2 genoemde subverwerkers die (deels) buiten de EER verwerken.

7.2 Doorgifte buiten de EER vindt uitsluitend plaats op basis van een adequaatheidsbesluit van de Europese Commissie (waaronder het EU-VS Data Privacy Framework voor gecertificeerde ontvangers) of de standaardcontractbepalingen van de Commissie (uitvoeringsbesluit (EU) 2021/914), waar nodig aangevuld met aanvullende maatregelen zoals versleuteling en pseudonimisering. AanloopAI stelt de gebruikte waarborgen op verzoek beschikbaar.

### Artikel 8 — Bijstand bij rechten van betrokkenen

8.1 Ontvangt AanloopAI een verzoek of klacht van een betrokkene dat betrekking heeft op de verwerking voor Opdrachtgever, dan stuurt zij dit binnen **3 werkdagen** door aan Opdrachtgever en reageert zij niet zelf inhoudelijk, tenzij Opdrachtgever daarom vraagt.

8.2 AanloopAI verleent Opdrachtgever, rekening houdend met de aard van de verwerking, redelijke bijstand bij het beantwoorden van verzoeken van betrokkenen (artikel 12 t/m 22 AVG), bijvoorbeeld door gegevens op te zoeken, te exporteren, te corrigeren of te verwijderen. Bijstand die meer dan twee uur per verzoek vergt, mag AanloopAI tegen haar uurtarief in rekening brengen.

### Artikel 9 — Inbreuk in verband met persoonsgegevens (datalek)

9.1 AanloopAI meldt een inbreuk in verband met persoonsgegevens die de voor Opdrachtgever verwerkte gegevens raakt **zonder onredelijke vertraging en uiterlijk binnen 36 uur** na ontdekking aan Opdrachtgever, via het in het Portaal opgegeven contactadres en per e-mail aan {{klant_contact_email}}. Zo kan Opdrachtgever de termijn van 72 uur van artikel 33 AVG halen.

9.2 De melding bevat, voor zover op dat moment bekend: de aard van de inbreuk, de categorieën en het geschatte aantal betrokkenen en gegevensregisters, de waarschijnlijke gevolgen, de genomen en voorgestelde maatregelen en een contactpunt. Informatie die later beschikbaar komt, wordt nagestuurd.

9.3 De beslissing om de inbreuk te melden bij de Autoriteit Persoonsgegevens en/of aan betrokkenen is aan Opdrachtgever. AanloopAI verleent daarbij redelijke bijstand en doet geen eigen melding of mededeling over de inbreuk zonder afstemming met Opdrachtgever, tenzij de wet dat van AanloopAI eist.

9.4 AanloopAI houdt een register bij van inbreuken die de gegevens van Opdrachtgever raken.

### Artikel 10 — Bijstand bij DPIA en voorafgaande raadpleging

10.1 AanloopAI verleent Opdrachtgever redelijke bijstand bij een gegevensbeschermingseffectbeoordeling (artikel 35 AVG) en een voorafgaande raadpleging van de toezichthouder (artikel 36 AVG), voor zover die betrekking hebben op de verwerking door AanloopAI. Artikel 8.2, laatste zin, is van overeenkomstige toepassing.

### Artikel 11 — Informatie en audit

11.1 AanloopAI stelt Opdrachtgever alle informatie ter beschikking die nodig is om aan te tonen dat aan artikel 28 AVG wordt voldaan, en beantwoordt redelijke schriftelijke vragen over de verwerking binnen 10 werkdagen.

11.2 Opdrachtgever mag ten hoogste **eenmaal per jaar**, of vaker als een inbreuk of een aanwijzing van de toezichthouder daartoe aanleiding geeft, een audit (laten) uitvoeren naar de naleving van deze Verwerkersovereenkomst. De audit wordt ten minste 14 dagen vooraf aangekondigd, vindt plaats tijdens kantooruren, verstoort de bedrijfsvoering van AanloopAI zo min mogelijk en wordt uitgevoerd door Opdrachtgever zelf of door een onafhankelijke, tot geheimhouding verplichte auditor die geen concurrent van AanloopAI is.

11.3 Beschikt AanloopAI of een subverwerker over een actueel certificaat of auditrapport (bijvoorbeeld ISO 27001 of SOC 2) dat de betreffende verwerking afdekt, dan mag AanloopAI dat in eerste instantie verstrekken ter voldoening aan de audit. Opdrachtgever behoudt het recht op aanvullend onderzoek als dat rapport zijn vragen niet beantwoordt.

11.4 De kosten van een audit draagt Opdrachtgever, tenzij de audit wezenlijke tekortkomingen van AanloopAI aantoont. AanloopAI mag haar redelijke medewerkingskosten in rekening brengen als de audit meer dan één werkdag van haar vergt.

### Artikel 12 — Einde van de verwerking

12.1 Bij het einde van de Overeenkomst, of zoveel eerder als Opdrachtgever daarom vraagt, stelt AanloopAI de persoonsgegevens gedurende **30 dagen** in een gangbaar formaat beschikbaar voor export door Opdrachtgever (zie ook artikel 16.5 van de Algemene Voorwaarden).

12.2 Na die periode, of direct na schriftelijke bevestiging van Opdrachtgever dat de export is geslaagd, verwijdert AanloopAI alle persoonsgegevens en kopieën daarvan, inclusief bij subverwerkers, binnen 30 dagen, tenzij Unierecht of Nederlands recht opslag voorschrijft. Back-ups worden volgens de normale rotatie (maximaal 90 dagen) overschreven en worden in de tussentijd niet actief gebruikt.

12.3 Op verzoek bevestigt AanloopAI de verwijdering schriftelijk.

### Artikel 13 — Aansprakelijkheid

13.1 De aansprakelijkheid van partijen jegens elkaar uit hoofde van deze Verwerkersovereenkomst is onderworpen aan artikel 14 van de Algemene Voorwaarden van AanloopAI.

13.2 Boetes van een toezichthouder draagt de partij aan wie de overtreding is toe te rekenen. Voor aansprakelijkheid jegens betrokkenen geldt artikel 82 AVG.

---

## DEEL II — LEADS: AFSPRAKEN TUSSEN ZELFSTANDIGE VERWERKINGSVERANTWOORDELIJKEN

### Artikel 14 — Verplichtingen van AanloopAI

14.1 AanloopAI verzamelt aanvragen op een Platform uitsluitend met uitdrukkelijke, gedocumenteerde toestemming van de aanvrager om door één aangesloten ondernemer te worden benaderd, informeert de aanvrager conform artikel 13 AVG en bewaart het bewijs van toestemming.

14.2 AanloopAI controleert de aanvraag op volledigheid en plausibiliteit vóór doorgifte en geeft de Lead uitsluitend door aan Opdrachtgever (exclusiviteit conform Module C van de Algemene Voorwaarden).

14.3 AanloopAI informeert de aanvrager bij bevestiging van de aanvraag over de identiteit van Opdrachtgever als ontvanger.

14.4 Ontvangt AanloopAI een intrekking van toestemming, een bezwaar of een verwijderverzoek van een aanvrager, dan geeft zij dit binnen 3 werkdagen door aan Opdrachtgever.

### Artikel 15 — Verplichtingen van Opdrachtgever

15.1 Opdrachtgever gebruikt Leadgegevens uitsluitend om de aanvraag te beantwoorden en voor de daaruit voortvloeiende klantrelatie. Doorverkoop, delen met derden, opname in marketinglijsten of nieuwsbrieven zonder eigen toestemming van de aanvrager, en gebruik voor andere doeleinden zijn niet toegestaan.

15.2 Opdrachtgever informeert de aanvrager bij het eerste contact over zijn identiteit en over de herkomst van de aanvraag (het Platform), en verwijst voor de verdere verwerking naar zijn eigen privacyverklaring.

15.3 Opdrachtgever beveiligt Leadgegevens passend (artikel 32 AVG), beperkt de toegang tot medewerkers die de Lead opvolgen, en bewaart Leadgegevens in een systeem met toegangsbeheer (geen losse spreadsheets of privé-telefoons zonder beveiliging).

15.4 Opdrachtgever respecteert een bezwaar of intrekking van toestemming van de aanvrager onmiddellijk en staakt dan ieder contact.

15.5 Opdrachtgever verwijdert of anonimiseert Leadgegevens uiterlijk **12 maanden** na ontvangst als geen klantrelatie is ontstaan.

15.6 Opdrachtgever meldt een inbreuk die Leadgegevens raakt binnen **48 uur** na ontdekking aan AanloopAI via m.dogan@aanloopai.nl, zodat AanloopAI aanvragers zo nodig kan informeren.

15.7 Opdrachtgever vrijwaart AanloopAI tegen aanspraken van aanvragers en toezichthouders die voortvloeien uit zijn verwerking van Leadgegevens.

### Artikel 16 — Samenwerking

16.1 Partijen verlenen elkaar redelijke medewerking bij verzoeken van aanvragers, klachten en onderzoeken van de toezichthouder die beide partijen raken, en informeren elkaar onverwijld over zulke verzoeken.

---

## DEEL III — SLOTBEPALINGEN

### Artikel 17 — Duur en rangorde

17.1 Deze Verwerkersovereenkomst treedt in werking bij ondertekening van de Overeenkomst en blijft gelden zolang AanloopAI persoonsgegevens voor of met Opdrachtgever verwerkt, en voor wat betreft de artikelen 4, 12 en 13 ook daarna.

17.2 Bij strijdigheid tussen deze Verwerkersovereenkomst en de Overeenkomst of Algemene Voorwaarden gaat, voor zover het de verwerking van persoonsgegevens betreft, deze Verwerkersovereenkomst voor.

17.3 Wijzigingen zijn alleen geldig als zij schriftelijk zijn overeengekomen, met uitzondering van wijzigingen in de bijlagen volgens de procedure van artikel 5.2 en 6.2.

### Artikel 18 — Toepasselijk recht

18.1 Op deze Verwerkersovereenkomst is Nederlands recht van toepassing. Geschillen worden voorgelegd aan de rechtbank Rotterdam.

---

## BIJLAGE 1 — Overzicht van verwerkingen (deel I)

| Onderdeel | Categorieën betrokkenen | Categorieën persoonsgegevens | Doel | Duur |
|---|---|---|---|---|
| Website {{project_domein}} — contactformulier, offerte-aanvraag, WhatsApp-knop | Bezoekers en (potentiële) klanten van Opdrachtgever | Naam, e-mail, telefoon, woonplaats/postcode, inhoud van het bericht, tijdstip, IP-adres (serverlogs) | Doorsturen van aanvragen aan Opdrachtgever, spampreventie | Formulierdata 12 maanden op de server, daarna automatisch verwijderd; serverlogs 30 dagen |
| Afspraakmodule | (Potentiële) klanten van Opdrachtgever | Naam, e-mail, telefoon, gekozen datum/tijd, opmerkingen | Inplannen van een showroomafspraak in de agenda van Opdrachtgever | Tot 12 maanden na de afspraak |
| Hosting en back-ups | Alle hierboven genoemden | Alle hierboven genoemde gegevens zoals opgeslagen in de website | Beschikbaarheid en herstel | Back-ups maximaal 90 dagen |
| Webstatistiek | Bezoekers | Geanonimiseerd IP, pagina''s, apparaat, browser, herkomst | Verbetering van de website en rapportage aan Opdrachtgever | 26 maanden |
| Reviewverzoek na montage (indien overeengekomen) | Klanten van Opdrachtgever | Naam, e-mail of telefoon, datum montage | Eenmalig verzoek om een review achter te laten | 3 maanden na verzending |
| AI-agent namens Opdrachtgever (indien overeengekomen) | Bezoekers en klanten van Opdrachtgever | Gespreksinhoud, contactgegevens die de gebruiker deelt, tijdstip | Vragen beantwoorden, afspraak of terugbelverzoek vastleggen | Gespreksinhoud 6 maanden |

Geen bijzondere categorieën persoonsgegevens; geen gegevens van minderjarigen als doelgroep.

## BIJLAGE 2 — Subverwerkers (stand 9 oktober 2026)

| Subverwerker | Dienst | Vestiging | Locatie verwerking | Waarborg doorgifte |
|---|---|---|---|---|
| Hetzner Online GmbH | Servers, opslag, back-ups | Gunzenhausen, Duitsland | Duitsland / Finland | n.v.t. (EU) |
| Cloudflare, Inc. | DNS, CDN, DDoS-bescherming, TLS | San Francisco, VS (EU-entiteit: Cloudflare Netherlands B.V.) | Wereldwijd netwerk; opslag EU waar mogelijk | DPF-gecertificeerd; SCC''s |
| mijn.host | Transactionele e-mail (verzending namens Portaal en website) | Nederland | Nederland | n.v.t. (EU) |
| Brevo (Sendinblue SAS) | E-mailverzending (bevestigingen, reviewverzoeken) | Parijs, Frankrijk | EU | n.v.t. (EU) |
| Google Ireland Ltd. | Google Analytics 4 (geanonimiseerd), Search Console, Google Bedrijfsprofiel | Dublin, Ierland | EU / VS | DPF-gecertificeerd; SCC''s |
| Meta Platforms Ireland Ltd. | WhatsApp Business (berichten tussen bezoeker en Opdrachtgever) | Dublin, Ierland | EU / VS | DPF-gecertificeerd; SCC''s |
| ElevenLabs, Inc. (alleen bij spraakagent) | Spraaksynthese en -herkenning | New York, VS | VS / EU | SCC''s; zero-retention-instelling |
| Anthropic, PBC en/of OpenAI, LLC (alleen bij AI-agent) | Taalmodel voor gespreksafhandeling | San Francisco, VS | VS | DPF-gecertificeerd (OpenAI) / SCC''s; API-voorwaarden zonder training op klantdata |

Wijzigingen worden conform artikel 6.2 aangekondigd.

## BIJLAGE 3 — Technische en organisatorische maatregelen

**Toegang en authenticatie**
- Persoonlijke accounts; geen gedeelde wachtwoorden; tweefactorauthenticatie op alle beheeraccounts (hosting, DNS, e-mail, code, Portaal-admin).
- Toegang tot servers uitsluitend via SSH-sleutels; wachtwoordlogin uitgeschakeld.
- Toegang tot klantaccounts (analytics, bedrijfsprofiel, agenda) alleen via uitnodiging op het account van Opdrachtgever; AanloopAI slaat geen wachtwoorden van Opdrachtgever op.
- Toegangsrechten worden bij einde van de Overeenkomst binnen 5 werkdagen ingetrokken.

**Versleuteling**
- Alle verbindingen via TLS 1.2 of hoger (HSTS ingeschakeld).
- Back-ups versleuteld opgeslagen; schijfversleuteling op servers waar de hostingpartij dit ondersteunt.
- Eenmalige inlogcodes en verificatiecodes worden gehasht opgeslagen en zijn beperkt geldig.

**Beschikbaarheid en herstel**
- Dagelijkse geautomatiseerde back-ups, bewaard tot maximaal 90 dagen, periodiek getest op herstelbaarheid.
- Monitoring van beschikbaarheid met waarschuwingen.
- Beveiligingsupdates van besturingssysteem en software binnen 14 dagen na uitgifte; kritieke updates zo snel mogelijk.

**Dataminimalisatie en scheiding**
- Formulieren vragen alleen de gegevens die nodig zijn voor de aanvraag.
- Gegevens van verschillende opdrachtgevers zijn logisch gescheiden.
- Geüploade bestanden en gegenereerde documenten zijn niet via publieke links bereikbaar; downloads via tijdelijk geldige, geauthenticeerde links.
- Automatische verwijdering volgens de bewaartermijnen in Bijlage 1.

**Logging en controle**
- Logging van inlogpogingen, toegang tot het Portaal en beheerhandelingen; logs 12 maanden bewaard.
- Jaarlijkse interne controle van toegangsrechten en subverwerkerslijst.

**Organisatie**
- AanloopAI werkt zonder personeel; ingeschakelde freelancers of partners tekenen een geheimhoudings- en verwerkersverklaring voordat zij toegang krijgen.
- Procedure voor inbreuken: detectie, insluiting, melding aan Opdrachtgever binnen 36 uur, analyse, herstel, registratie.
- Apparatuur van AanloopAI is versleuteld en voorzien van schermvergrendeling en actuele beveiligingssoftware.

---

*Einde Privacyverklaring en Verwerkersovereenkomst AanloopAI, versie 1.0.*
', 1760000000000, 1760000000000);
